### PR TITLE
revert: "ci(reqs): rename requirements to constraints"

### PR DESCRIPTION
**Pull request by sileht**
Dependabot does not support symlink.

This reverts commit c85afc1e47d4916884abdab54c46e9510a785dfd.

Change-Id: I1d39fd4d3a5ac943ffbefb9e3a7ad2e36eb4650d

### CODE REVIEW

**Comment by sileht** [comment]
Dependabot has deleted the symlink https://github.com/Mergifyio/mergify-engine/pull/4905/files

**Comment by jd** [comment]
Dependabot duplicated the file 😢 
Might be better to just fix the code in the prod repo though.

**Review by jd — APPROVED** [review]

**Review by jd — CHANGES_REQUESTED** [review]
missing requirements.txt?

**Comment by sileht** [comment]
> missing requirements.txt?

it's already in the repo

**Pull request merged**
