### PR TITLE
fix(github_events): also send initial summary on synchronize events

### PR DESCRIPTION
**Pull request by jd**
This should make sure the Mergify summary reappears as in progress as soon as
new commits are pushed.

### CODE REVIEW

**Review by sileht — APPROVED** [review]

**Comment by sileht** [comment]
If we do that, we also need to update: https://github.com/Mergifyio/mergify-engine/blob/master/mergify_engine/engine/__init__.py#L91-L94

**Comment by sileht** [comment]
Hum I re self-requested my review to avoid automerge but it hasn't worked.

**Comment by sileht** [comment]
> Hum I re self-requested my review to avoid automerge but it hasn't worked.

We don't use `#review-requested=0` so Mergify didn't care of my self-review-request.

**Comment by jd** [comment]
@sileht no you need to change your review to -1

I'm not sure about why we need to check the summary. IIUC when synchronize happens there's 0 check run so we can post this first one as soon as we have the event being queued in the worker.
What wrong can happen?

**Comment by sileht** [comment]
We store the state of the PR in the summary, on synchronize we copy the last known summary to the last head sha. We can't rely on event type to do the copy because engine may run after the git push but before we get the event. So the method a point copy it only when the summary is missing. We we create an empty summary the copy won't happen and we lost the state of the PR.

**Comment by sileht** [comment]
This change is a good idea, but if we do it we must update `ensure_summary_on_head_sha()` to take care of this case to copy the last know summary also when the content of the current one is the temporary one.

**Pull request merged**
