### PR TITLE
fix(seats-count): allow to use a dedicated db

### PR DESCRIPTION
**Pull request by sileht**
Fixes MRGFY-819

Change-Id: Ided4b76e680140b57d1c0afb772c4253922676ed

### CODE REVIEW

**Comment by sileht** [comment]
I didn't though how to move data to the new DB yet.

**Review by jd — CHANGES_REQUESTED** [review]
There seems to be no plan for migration?

**Review by jd — APPROVED** [review]

**Comment by sileht** [comment]
Lua scripts to move the data:

```
redis.call("SELECT", 2)
local matches = redis.call('KEYS', 'active-users~*')
local total = 0
local success = 0
for _,key in ipairs(matches) do
    local ret = redis.call('COPY', key, key, "DB", 8, "REPLACE")
    success = success + tonumber(ret)
    total = total + 1
end
return "Number of keys migrated: " .. success .. "/" .. total
```

Old data will expire itself.

**Comment by sileht** [comment]
@mergifyio rebase

**Pull request merged**
