### PR TITLE
actions/merge: handle \r\n line terminator

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Comment by jd** [comment]
@mergifyio rebase

**Comment by jd** [comment]
@Mergifyio rebase

**Comment by jd** [comment]
@mergifyio rebase

**Comment by jd** [comment]
@mergifyio rebase

**Comment by sileht** [comment]
@mergifyio rebase

**Comment by jd** [comment]
@mergifyio rebase

**Comment by sileht** [comment]
@Mergifyio rebase

**Comment by sileht** [comment]
@Mergifyio rebase

**Comment by sileht** [comment]
@mergifyio rebase

**Comment by sileht** [comment]
@mergifyio rebase

**Pull request merged**
