### PR TITLE
fix(engine): don't shallow unexpected jinja issue

### PR DESCRIPTION
**Pull request by GuillaumeOj**
We need to reimplement  3e6a737 correctly and more importantly, we should have caught the issue with our tests.

### CODE REVIEW

**Comment by jd** [comment]
This is good. I also don't understand why it works and how we break it in the first place.
I suggest keeping this as-is for now. I'll try to spend more time digging into it.

**Comment by sileht** [comment]
I found what I missed, I change `PullRequestRulesSchema` and missed to update`PullRequestRules.from_list`.

I still wonder why no test have catch that.

**Comment by sileht** [comment]
Can we just have the added tests in PR ? Even if they don't catch the issue we are looking for, they are a good addition to the test suite.

**Comment by GuillaumeOj** [comment]
> Can we just have the added tests in PR ? Even if they don't catch the issue we are looking for, they are a good addition to the test suite.

Done

**Review by jd — APPROVED** [review]

**Pull request merged**
