### PR TITLE
feat(context): less verbose __repr__

### PR DESCRIPTION
**Pull request by sileht**
Remove some attributes from __repr__ output.

### CODE REVIEW

**Review by jd — APPROVED** [review]
Why not passing repr=False to the attributes you don't want?

**Review by jd — CHANGES_REQUESTED** [review]
No I didn't want to approve 😁

**Comment by sileht** [comment]
> Why not passing repr=False to the attributes you don't want?

Because I didn't `field()` has repr :yum:

**Comment by sileht** [comment]
We can't implement __repr__ for TypedDict(). This is maybe still a bit too verbse.

Let's see how it goes.

**Review by jd — APPROVED** [review]

**Pull request merged**
