### PR TITLE
Drop engine v1

### PR DESCRIPTION
**Pull request by sileht**

### CODE REVIEW

**Comment by jd** [comment]
Let's not merge before Feb 1st.

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 202ea758c57508c7c3429d50d8ccd7871a1e1a3a

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 3cdc55dea79159b46653f8b7752d79952b184822

**Comment by sileht** [comment]
Pull-request updated, HEAD is now f29dc04f6727ba58bc477a4f92a2556bccefeda6

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 12a5ce655bf95d753ed75cc84c3368adc1182681

**Comment by sileht** [comment]
Pull-request updated, HEAD is now a47d90923d54908f27d5c26229da8ecb199ab9f8

**Comment by sileht** [comment]
Pull-request updated, HEAD is now dfb8e2717bbc2f7173d04858eb5f5cc0cf4f89d5

**Comment by sileht** [comment]
Pull-request updated, HEAD is now d34b50d9015c4f8954e858068ecf804a269d2a55

**Comment by sileht** [comment]
-1.5% coverage, I think we are good now!

**Pull request merged**
