### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by TomoyukiAota**

### CODE REVIEW

**Comment by TomoyukiAota** [comment]
Hi,

I saw Semantic Pull Request failed.
What should the commit message look like in this case?

**Review by jd — APPROVED** [review]
Thanks a lot for the fix @TomoyukiAota !

Your commit title should be something like:

```
docs(conditions): fix typo
```

**Comment by TomoyukiAota** [comment]
@jd 
Thanks, the commit message is fixed.

**Review by jd — APPROVED** [review]

**Comment by jd** [comment]
(I've closed/reopen to retrigger CircleCI)

**Pull request merged**
