### PR TITLE
chore():ignore .docker

### PR DESCRIPTION
**Pull request by Zerdanes**
add .docker to .gitignore

### CODE REVIEW

**Review by sileht — COMMENTED** [review]
.docker is not a file generated by the project, if you need to ignore file generated by your environment you should the global git config.

**Comment by jd** [comment]
It's actually generated by the project via `docker-compose`.

**Comment by sileht** [comment]
> It's actually generated by the project via `docker-compose`.

Not my docker-compose... I imagine it's a joke of the new version...

**Comment by sileht** [comment]
You need to remove the  `.gitignore.swp` file from the commit then.

**Review by sileht — DISMISSED** [review]
You need to remove the ` .gitignore.swp` file from the commit then.

**Review by sileht — CHANGES_REQUESTED** [review]
` .gitignore.swp` is still there.

**Review by jd — APPROVED** [review]

**Review by jd — APPROVED** [review]

**Pull request merged**
