### PR TITLE
fix(queue): preserve order when train is shrunk

### PR DESCRIPTION
**Pull request by sileht**
Change-Id: I9ca0063b0794320f502e3e1e92db51ec2bdf38b0

### CODE REVIEW

**Comment by sileht** [comment]
This pull request is part of a stack:
1. fix(queue): preserve order when train is skrink ([#2960](https://github.com/Mergifyio/mergify-engine/pull/2960))
1. chore(rules): add type to QueueRules ([#2961](https://github.com/Mergifyio/mergify-engine/pull/2961))
1. feat(queue): sync configuration of queued PR ([#2962](https://github.com/Mergifyio/mergify-engine/pull/2962))

**Comment by sileht** [comment]
test coverage is part of  https://github.com/Mergifyio/mergify-engine/pull/2962

**Comment by jd** [comment]
typo in title -> "shrunk"

**Review by jd — CHANGES_REQUESTED** [review]
can you fix the typo?

**Review by jd — CHANGES_REQUESTED** [review]
still typo @sileht

**Review by jd — APPROVED** [review]

**Pull request merged**
