### PR TITLE
feat(request-review): allow bot_account

### PR DESCRIPTION
**Pull request by sileht**
Fixes MRGFY-767

Change-Id: I3c30b2a4cd6b0c853c83db28866f73f06ae7176a

### CODE REVIEW

**Review by jd — CHANGES_REQUESTED** [review]
doc

**Review by jd — CHANGES_REQUESTED** [review]

**Comment by sileht** [comment]
@mergifyio squash

**Review by jd — CHANGES_REQUESTED** [review]
Release note?

**Comment by sileht** [comment]
> Release note?

https://github.com/Mergifyio/mergify-engine/pull/3745/files#diff-6a4e16bf9e1eea6ec7df20cd5dab217bbe8f0ba52b15f0c6450b79b674864b97

**Review by jd — APPROVED** [review]

**Pull request merged**
